"""deleted embedding field from document table

Revision ID: 993abf7ca524
Revises: 87299049816b
Create Date: 2025-06-18 00:08:51.820687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '993abf7ca524'
down_revision = '87299049816b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
